# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: car_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61r_service.proto\"!\n\x0bSyncRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\"0\n\x03\x43\x61r\x12\x0c\n\x04make\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x0c\n\x04year\x18\x03 \x01(\x05\"G\n\x0cSyncResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\x04\x63\x61rs\x18\x02 \x03(\x0b\x32\x04.Car\x12\x13\n\x0btotal_count\x18\x03 \x01(\x05\x32\x38\n\nCarService\x12*\n\x0bSyncCarData\x12\x0c.SyncRequest\x1a\r.SyncResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'car_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SYNCREQUEST']._serialized_start=21
  _globals['_SYNCREQUEST']._serialized_end=54
  _globals['_CAR']._serialized_start=56
  _globals['_CAR']._serialized_end=104
  _globals['_SYNCRESPONSE']._serialized_start=106
  _globals['_SYNCRESPONSE']._serialized_end=177
  _globals['_CARSERVICE']._serialized_start=179
  _globals['_CARSERVICE']._serialized_end=235
# @@protoc_insertion_point(module_scope)
